export type PublicTopicCluster = {
  name: string;
  tier: 'HIGH' | 'MEDIUM' | 'LOW';
  exams: number;
};

export type PublicCoursePreview = {
  code: string;
  name: string;
  year: number;
  stream: string | null;
  questionCount: number;
  clusters: PublicTopicCluster[];
};

export const PUBLIC_CONCEPT_PREVIEWS: PublicCoursePreview[] = [
  {
    code: 'MPC-001',
    name: 'Cognitive Psychology, Learning and Memory',
    year: 1,
    stream: null,
    questionCount: 118,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Working Memory and Information Processing' },
      { tier: 'HIGH', exams: 8, name: 'Classical and Operant Conditioning' },
      { tier: 'HIGH', exams: 8, name: 'Attention, Perception, and Pattern Recognition' },
      { tier: 'MEDIUM', exams: 5, name: 'Encoding, Storage, and Retrieval' },
      { tier: 'MEDIUM', exams: 5, name: 'Problem Solving and Decision Making' },
      { tier: 'LOW', exams: 3, name: 'Language, Thought, and Imagery' },
      { tier: 'LOW', exams: 3, name: 'Forgetting, Interference, and Memory Distortions' },
      { tier: 'LOW', exams: 3, name: 'Cognitive Neuroscience and Brain Mechanisms' },
      { tier: 'LOW', exams: 2, name: 'Concept Formation and Categorisation' },
      { tier: 'LOW', exams: 2, name: 'Motivation, Emotion, and Cognition' },
      { tier: 'LOW', exams: 2, name: 'Creativity and Intelligence' },
      { tier: 'LOW', exams: 2, name: 'Applications of Cognitive Psychology' },
    ],
  },
  {
    code: 'MPC-002',
    name: 'Life Span Psychology',
    year: 1,
    stream: null,
    questionCount: 104,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Piaget, Vygotsky, and Cognitive Development' },
      { tier: 'HIGH', exams: 8, name: 'Attachment and Socio-Emotional Development' },
      { tier: 'HIGH', exams: 7, name: 'Adolescence, Identity, and Peer Relations' },
      { tier: 'MEDIUM', exams: 5, name: 'Prenatal and Infancy Development' },
      { tier: 'MEDIUM', exams: 4, name: 'Adulthood, Ageing, and Life Events' },
      { tier: 'LOW', exams: 3, name: 'Developmental Research Methods' },
      { tier: 'LOW', exams: 3, name: 'Moral Development and Gender Role Development' },
      { tier: 'LOW', exams: 3, name: 'Language Development and School Readiness' },
      { tier: 'LOW', exams: 2, name: 'Parenting Styles and Family Influences' },
      { tier: 'LOW', exams: 2, name: 'Middle Childhood and Peer Competence' },
      { tier: 'LOW', exams: 2, name: 'Late Adulthood, Death, and Dying' },
      { tier: 'LOW', exams: 2, name: 'Developmental Hazards and Interventions' },
    ],
  },
  {
    code: 'MPC-003',
    name: 'Personality: Theories and Assessment',
    year: 1,
    stream: null,
    questionCount: 111,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Trait Theories and Big Five' },
      { tier: 'HIGH', exams: 8, name: 'Psychoanalytic and Neo-Freudian Views' },
      { tier: 'HIGH', exams: 7, name: 'Humanistic and Existential Approaches' },
      { tier: 'MEDIUM', exams: 5, name: 'Personality Assessment and Inventories' },
      { tier: 'MEDIUM', exams: 5, name: 'Social Learning and Cognitive Views' },
      { tier: 'LOW', exams: 3, name: 'Indian Perspectives on Personality' },
      { tier: 'LOW', exams: 3, name: 'Type and Factor Approaches' },
      { tier: 'LOW', exams: 3, name: 'Self, Identity, and Self-Concept' },
      { tier: 'LOW', exams: 2, name: 'Motivation and Personality Dynamics' },
      { tier: 'LOW', exams: 2, name: 'Culture and Personality' },
      { tier: 'LOW', exams: 2, name: 'Biological Bases of Personality' },
      { tier: 'LOW', exams: 2, name: 'Personality Development and Change' },
    ],
  },
  {
    code: 'MPC-004',
    name: 'Advanced Social Psychology',
    year: 1,
    stream: null,
    questionCount: 96,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Attitudes, Persuasion, and Attitude Change' },
      { tier: 'HIGH', exams: 8, name: 'Prejudice, Stereotypes, and Discrimination' },
      { tier: 'HIGH', exams: 7, name: 'Group Dynamics and Leadership' },
      { tier: 'MEDIUM', exams: 5, name: 'Aggression and Prosocial Behaviour' },
      { tier: 'MEDIUM', exams: 4, name: 'Attribution and Social Cognition' },
      { tier: 'LOW', exams: 3, name: 'Interpersonal Attraction and Relationships' },
      { tier: 'LOW', exams: 3, name: 'Conformity, Compliance, and Obedience' },
      { tier: 'LOW', exams: 3, name: 'Social Identity and Self in Groups' },
      { tier: 'LOW', exams: 2, name: 'Crowd Behaviour and Collective Action' },
      { tier: 'LOW', exams: 2, name: 'Environmental and Applied Social Psychology' },
      { tier: 'LOW', exams: 2, name: 'Social Influence and Propaganda' },
      { tier: 'LOW', exams: 2, name: 'Research Methods in Social Psychology' },
    ],
  },
  {
    code: 'MPC-005',
    name: 'Research Methods in Psychology',
    year: 1,
    stream: null,
    questionCount: 109,
    clusters: [
      { tier: 'HIGH', exams: 10, name: 'Sampling Methods and Research Design' },
      { tier: 'HIGH', exams: 9, name: 'Experimental, Quasi-Experimental, and Correlational Methods' },
      { tier: 'HIGH', exams: 8, name: 'Reliability, Validity, and Test Construction' },
      { tier: 'MEDIUM', exams: 5, name: 'Qualitative Research and Case Study' },
      { tier: 'MEDIUM', exams: 5, name: 'Hypothesis, Variables, and Operational Definitions' },
      { tier: 'LOW', exams: 3, name: 'Ethics and Report Writing' },
      { tier: 'LOW', exams: 3, name: 'Observation, Interview, and Survey Methods' },
      { tier: 'LOW', exams: 3, name: 'Content Analysis and Grounded Theory' },
      { tier: 'LOW', exams: 2, name: 'Single-Case and Field Research Designs' },
      { tier: 'LOW', exams: 2, name: 'Data Collection Tools and Scaling' },
      { tier: 'LOW', exams: 2, name: 'Review of Literature and Research Problem' },
      { tier: 'LOW', exams: 2, name: 'APA Style and Research Proposal Writing' },
    ],
  },
  {
    code: 'MPC-006',
    name: 'Statistics in Psychology',
    year: 1,
    stream: null,
    questionCount: 92,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Correlation, Regression, and Prediction' },
      { tier: 'HIGH', exams: 8, name: 't-Test, ANOVA, and Significance Testing' },
      { tier: 'HIGH', exams: 7, name: 'Measures of Central Tendency and Variability' },
      { tier: 'MEDIUM', exams: 5, name: 'Normal Probability Curve and Standard Scores' },
      { tier: 'MEDIUM', exams: 4, name: 'Non-Parametric Statistics' },
      { tier: 'LOW', exams: 3, name: 'Graphical Representation of Data' },
      { tier: 'LOW', exams: 3, name: 'Probability, Sampling Distribution, and Standard Error' },
      { tier: 'LOW', exams: 3, name: 'Chi-Square and Contingency Tables' },
      { tier: 'LOW', exams: 2, name: 'Percentiles, Quartiles, and Norms' },
      { tier: 'LOW', exams: 2, name: 'Effect Size and Statistical Power' },
      { tier: 'LOW', exams: 2, name: 'Descriptive Statistics and Data Cleaning' },
      { tier: 'LOW', exams: 2, name: 'Computer Applications in Psychological Statistics' },
    ],
  },
  {
    code: 'MPCE-011',
    name: 'Abnormal Psychology',
    year: 2,
    stream: 'Clinical',
    questionCount: 122,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Classification, Diagnosis, and DSM Framework' },
      { tier: 'HIGH', exams: 9, name: 'Anxiety, Obsessive-Compulsive, and Related Disorders' },
      { tier: 'HIGH', exams: 8, name: 'Mood Disorders and Suicide Risk' },
      { tier: 'HIGH', exams: 7, name: 'Schizophrenia and Psychotic Disorders' },
      { tier: 'MEDIUM', exams: 5, name: 'Personality Disorders' },
      { tier: 'MEDIUM', exams: 4, name: 'Somatic, Dissociative, and Trauma-Related Disorders' },
      { tier: 'LOW', exams: 3, name: 'Substance-Related and Addictive Disorders' },
      { tier: 'LOW', exams: 3, name: 'Eating, Sleep, and Sexual Disorders' },
      { tier: 'LOW', exams: 2, name: 'Childhood and Neurodevelopmental Disorders' },
      { tier: 'LOW', exams: 2, name: 'Biological and Psychosocial Models of Abnormality' },
      { tier: 'LOW', exams: 2, name: 'Stress, Coping, and Adjustment Disorders' },
      { tier: 'LOW', exams: 2, name: 'Prevention, Rehabilitation, and Community Care' },
    ],
  },
  {
    code: 'MPCE-012',
    name: 'Psychodiagnostics',
    year: 2,
    stream: 'Clinical',
    questionCount: 98,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Clinical Interview and Case History' },
      { tier: 'HIGH', exams: 8, name: 'Intelligence and Neuropsychological Assessment' },
      { tier: 'HIGH', exams: 7, name: 'Projective Techniques and Personality Testing' },
      { tier: 'MEDIUM', exams: 5, name: 'Mental Status Examination' },
      { tier: 'MEDIUM', exams: 4, name: 'Behavioural Assessment and Rating Scales' },
      { tier: 'LOW', exams: 3, name: 'Ethical Issues in Psychological Testing' },
      { tier: 'LOW', exams: 3, name: 'Diagnostic Formulation and Differential Diagnosis' },
      { tier: 'LOW', exams: 3, name: 'Assessment of Anxiety, Mood, and Psychotic Disorders' },
      { tier: 'LOW', exams: 2, name: 'Child and Adolescent Assessment' },
      { tier: 'LOW', exams: 2, name: 'Screening Tools and Clinical Scales' },
      { tier: 'LOW', exams: 2, name: 'Cultural Issues in Psychodiagnostics' },
      { tier: 'LOW', exams: 2, name: 'Feedback, Referral, and Documentation' },
    ],
  },
  {
    code: 'MPCE-013',
    name: 'Psychotherapeutic Methods',
    year: 2,
    stream: 'Clinical',
    questionCount: 106,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Cognitive Behaviour Therapy' },
      { tier: 'HIGH', exams: 8, name: 'Psychoanalytic and Psychodynamic Therapy' },
      { tier: 'HIGH', exams: 7, name: 'Behaviour Therapy and Systematic Desensitisation' },
      { tier: 'MEDIUM', exams: 5, name: 'Humanistic and Existential Therapy' },
      { tier: 'MEDIUM', exams: 4, name: 'Family and Group Therapy' },
      { tier: 'LOW', exams: 3, name: 'Therapeutic Relationship and Termination' },
      { tier: 'LOW', exams: 3, name: 'Supportive, Brief, and Crisis Psychotherapy' },
      { tier: 'LOW', exams: 3, name: 'REBT and Cognitive Restructuring' },
      { tier: 'LOW', exams: 2, name: 'Mindfulness and Third-Wave Therapies' },
      { tier: 'LOW', exams: 2, name: 'Play, Art, and Expressive Therapies' },
      { tier: 'LOW', exams: 2, name: 'Indications, Contraindications, and Case Planning' },
      { tier: 'LOW', exams: 2, name: 'Ethical and Professional Issues in Therapy' },
    ],
  },
  {
    code: 'MPCE-021',
    name: 'Counselling Psychology',
    year: 2,
    stream: 'Counselling',
    questionCount: 121,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Depression: Causes, Symptoms, and Treatment' },
      { tier: 'HIGH', exams: 9, name: 'Child Rights, Abuse, and Vulnerable Children' },
      { tier: 'HIGH', exams: 8, name: 'Psychoanalytic and Adlerian Approaches' },
      { tier: 'HIGH', exams: 8, name: 'Counselling Process and Relationship' },
      { tier: 'HIGH', exams: 8, name: 'Ethics and Professional Issues in Counselling' },
      { tier: 'HIGH', exams: 8, name: 'Personality Disorders' },
      { tier: 'HIGH', exams: 7, name: 'Eating Disorders' },
      { tier: 'MEDIUM', exams: 5, name: 'Person-Centered and Existential Approaches' },
      { tier: 'MEDIUM', exams: 5, name: 'Cognitive Behavioral and Rational Emotive Therapy' },
      { tier: 'HIGH', exams: 6, name: 'Behavioural Techniques and Systematic Desensitization' },
      { tier: 'HIGH', exams: 6, name: 'Solution-Focused Brief Therapy' },
      { tier: 'HIGH', exams: 6, name: 'Addiction, Anxiety, and Related Disorders' },
      { tier: 'MEDIUM', exams: 5, name: 'Art, Drama, and Creative Therapies' },
      { tier: 'MEDIUM', exams: 5, name: 'Basic Concepts and Miscellaneous Topics' },
      { tier: 'MEDIUM', exams: 5, name: 'Other Topics' },
      { tier: 'MEDIUM', exams: 4, name: 'Gestalt and Transactional Analysis' },
      { tier: 'MEDIUM', exams: 4, name: 'Educational and Vocational Counselling' },
      { tier: 'MEDIUM', exams: 3, name: 'HIV/AIDS Counselling and Special Populations' },
    ],
  },
  {
    code: 'MPCE-022',
    name: 'Assessment in Counselling and Guidance',
    year: 2,
    stream: 'Counselling',
    questionCount: 87,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Aptitude, Interest, and Personality Assessment' },
      { tier: 'HIGH', exams: 8, name: 'Guidance Needs Across Developmental Stages' },
      { tier: 'HIGH', exams: 7, name: 'Career Counselling and Vocational Guidance' },
      { tier: 'MEDIUM', exams: 5, name: 'Test Selection, Administration, and Interpretation' },
      { tier: 'MEDIUM', exams: 4, name: 'Assessment Report Writing' },
      { tier: 'LOW', exams: 3, name: 'Ethical Issues in Assessment' },
      { tier: 'LOW', exams: 3, name: 'Counselling Interview and Observation' },
      { tier: 'LOW', exams: 3, name: 'Educational Assessment and Guidance Records' },
      { tier: 'LOW', exams: 2, name: 'Individual Differences and Special Needs Assessment' },
      { tier: 'LOW', exams: 2, name: 'Group Testing and Screening' },
      { tier: 'LOW', exams: 2, name: 'Assessment Feedback and Counselling Planning' },
      { tier: 'LOW', exams: 2, name: 'Use of Technology in Counselling Assessment' },
    ],
  },
  {
    code: 'MPCE-023',
    name: 'Interventions in Counselling',
    year: 2,
    stream: 'Counselling',
    questionCount: 94,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Crisis Intervention and Suicide Prevention' },
      { tier: 'HIGH', exams: 8, name: 'Family, Marriage, and Relationship Counselling' },
      { tier: 'HIGH', exams: 7, name: 'Substance Abuse and Rehabilitation Counselling' },
      { tier: 'MEDIUM', exams: 5, name: 'School and Adolescent Counselling' },
      { tier: 'MEDIUM', exams: 4, name: 'Group Counselling and Support Groups' },
      { tier: 'LOW', exams: 3, name: 'Community and Multicultural Counselling' },
      { tier: 'LOW', exams: 3, name: 'Trauma, Grief, and Bereavement Counselling' },
      { tier: 'LOW', exams: 3, name: 'HIV/AIDS and Health Counselling Interventions' },
      { tier: 'LOW', exams: 2, name: 'Career and Workplace Counselling Interventions' },
      { tier: 'LOW', exams: 2, name: 'Counselling Children with Special Needs' },
      { tier: 'LOW', exams: 2, name: 'Rehabilitation and Disability Counselling' },
      { tier: 'LOW', exams: 2, name: 'Evaluation of Counselling Interventions' },
    ],
  },
  {
    code: 'MPCE-031',
    name: 'Organisational Behaviour',
    year: 2,
    stream: 'Organisational',
    questionCount: 101,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Motivation, Morale, and Job Satisfaction' },
      { tier: 'HIGH', exams: 8, name: 'Leadership Styles and Theories' },
      { tier: 'HIGH', exams: 8, name: 'Organisational Culture and Climate' },
      { tier: 'MEDIUM', exams: 5, name: 'Group Dynamics and Team Building' },
      { tier: 'MEDIUM', exams: 5, name: 'Conflict, Power, and Politics' },
      { tier: 'LOW', exams: 3, name: 'Communication in Organisations' },
      { tier: 'LOW', exams: 3, name: 'Perception, Attitudes, and Values at Work' },
      { tier: 'LOW', exams: 3, name: 'Job Stress, Burnout, and Coping' },
      { tier: 'LOW', exams: 2, name: 'Organisational Commitment and Citizenship Behaviour' },
      { tier: 'LOW', exams: 2, name: 'Decision Making and Problem Solving' },
      { tier: 'LOW', exams: 2, name: 'Work Motivation Theories and Applications' },
      { tier: 'LOW', exams: 2, name: 'Diversity, Inclusion, and Workplace Ethics' },
    ],
  },
  {
    code: 'MPCE-032',
    name: 'Human Resource Development',
    year: 2,
    stream: 'Organisational',
    questionCount: 88,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Training Needs Analysis and Evaluation' },
      { tier: 'HIGH', exams: 8, name: 'Performance Appraisal and Feedback' },
      { tier: 'HIGH', exams: 7, name: 'Career Planning and Development' },
      { tier: 'MEDIUM', exams: 5, name: 'Competency Mapping and Assessment Centres' },
      { tier: 'MEDIUM', exams: 4, name: 'Employee Counselling and Wellness' },
      { tier: 'LOW', exams: 3, name: 'HRD Climate and Audit' },
      { tier: 'LOW', exams: 3, name: 'Recruitment, Selection, and Placement' },
      { tier: 'LOW', exams: 3, name: 'Learning Principles and Training Methods' },
      { tier: 'LOW', exams: 2, name: 'Mentoring, Coaching, and Leadership Development' },
      { tier: 'LOW', exams: 2, name: 'Reward Systems and Employee Engagement' },
      { tier: 'LOW', exams: 2, name: 'Talent Management and Succession Planning' },
      { tier: 'LOW', exams: 2, name: 'HRD in Indian Organisations' },
    ],
  },
  {
    code: 'MPCE-033',
    name: 'Organisational Development',
    year: 2,
    stream: 'Organisational',
    questionCount: 82,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'OD Values, Process, and Action Research' },
      { tier: 'HIGH', exams: 8, name: 'Change Management and Resistance' },
      { tier: 'HIGH', exams: 7, name: 'Team Interventions and Survey Feedback' },
      { tier: 'MEDIUM', exams: 5, name: 'Sensitivity Training and Process Consultation' },
      { tier: 'MEDIUM', exams: 4, name: 'Quality of Work Life' },
      { tier: 'LOW', exams: 3, name: 'Learning Organisations' },
      { tier: 'LOW', exams: 3, name: 'Diagnosis, Feedback, and Intervention Design' },
      { tier: 'LOW', exams: 3, name: 'Structural and Strategic Interventions' },
      { tier: 'LOW', exams: 2, name: 'Large Group and Intergroup Interventions' },
      { tier: 'LOW', exams: 2, name: 'Organisational Effectiveness and Culture Change' },
      { tier: 'LOW', exams: 2, name: 'OD Consultant Role and Ethics' },
      { tier: 'LOW', exams: 2, name: 'Evaluating and Institutionalising OD' },
    ],
  },
  {
    code: 'MPCE-046',
    name: 'Applied Positive Psychology',
    year: 2,
    stream: 'Common',
    questionCount: 76,
    clusters: [
      { tier: 'HIGH', exams: 9, name: 'Happiness, Well-Being, and Life Satisfaction' },
      { tier: 'HIGH', exams: 8, name: 'Character Strengths and Virtues' },
      { tier: 'HIGH', exams: 7, name: 'Resilience, Hope, and Optimism' },
      { tier: 'MEDIUM', exams: 5, name: 'Positive Emotions and Flow' },
      { tier: 'MEDIUM', exams: 4, name: 'Positive Interventions in Education and Work' },
      { tier: 'LOW', exams: 3, name: 'Mindfulness, Gratitude, and Forgiveness' },
      { tier: 'LOW', exams: 3, name: 'Meaning, Purpose, and Post-Traumatic Growth' },
      { tier: 'LOW', exams: 3, name: 'Positive Relationships and Compassion' },
      { tier: 'LOW', exams: 2, name: 'Assessment of Well-Being and Strengths' },
      { tier: 'LOW', exams: 2, name: 'Positive Ageing and Health' },
      { tier: 'LOW', exams: 2, name: 'Indian Perspectives on Positive Living' },
      { tier: 'LOW', exams: 2, name: 'Critiques and Future Directions in Positive Psychology' },
    ],
  },
];
